# Generated by Django 2.0.7 on 2018-07-09 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createAt',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 22, 19, 40, 903992)),
        ),
        migrations.AlterField(
            model_name='category',
            name='createAt',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 22, 19, 40, 893749)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='createAt',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 22, 19, 40, 903334)),
        ),
    ]
