# Generated by Django 2.0.7 on 2018-07-09 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180709_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createAt',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 23, 4, 35, 730554)),
        ),
        migrations.AlterField(
            model_name='category',
            name='createAt',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 23, 4, 35, 719909)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='createAt',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 23, 4, 35, 729919)),
        ),
    ]
